language: ruby
before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do yes | gem install bundler -v '< 2.0.0'
script: bundle exec rspec
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - ruby-head
gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
jobs:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails_6.gemfile