language: ruby
before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do yes | gem install bundler -v '< 2.0.0'
script: bundle exec appraisal rspec
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head