language: ruby
script: bundle exec rspec
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - ruby-head
gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails_6.gemfile