language: ruby
before_install: 
  - rvm @global do gem install bundler -v '< 2.0.0'
  - cd spec/rails-app && BUNDLE_GEMFILE=$TRAVIS_BUILD_DIR/spec/rails-app/Gemfile bundle install && cd ../..
script: bundle exec rspec
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
